apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      # must be commented out for network host
      # serviceAccountName: default-full-access-mounted
      containers:
        - name: {{ .Release.Name }}-ca-gateway
          command:
           - bash
          args:
           - "/config/start-ca.sh"
          env:
            # IMPORTANT - set this to YES for network host or NO for internal network
            - name: EPICS_CA_AUTO_ADDR_LIST
              value: "YES"
            - name: CA_SERVER_PORT
              value: "9064"
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 1500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                - NET_RAW
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - SETFCAP
                - SETGID
                - SETPCAP
                - SETUID
                - SYS_CHROOT
                - AUDIT_CONTROL
                - BLOCK_SUSPEND
                - DAC_READ_SEARCH
                - IPC_LOCK
                - IPC_OWNER
                - LEASE
                - LINUX_IMMUTABLE
                - MAC_ADMIN
                - MAC_OVERRIDE
                - SYS_ADMIN
                - SYS_BOOT
                - SYS_MODULE
                - SYS_NICE
                - SYS_PACCT
                - SYS_PTRACE
                - SYS_RESOURCE
                - SYS_TIME
                - SYS_TTY_CONFIG
                - SYSLOG
                - WAKE_ALARM
          stdin: true
          tty: true
        - name: "{{ .Release.Name }}-pva-gateway"
          command:
           - bash
          args:
           - "/config/start-pva.sh"
          env:
            # IMPORTANT - set this to YES for net=host or NO for internal network
            - name: EPICS_PVA_AUTO_ADDR_LIST
              value: "YES"
            - name: PVA_SERVER_PORT
              value: "9065"
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 1500Mi
            requests:
              cpu: 200m
              memory: 400Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                - NET_RAW
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - MKNOD
                - NET_BIND_SERVICE
                - SETFCAP
                - SETGID
                - SETPCAP
                - SETUID
                - SYS_CHROOT
                - AUDIT_CONTROL
                - BLOCK_SUSPEND
                - DAC_READ_SEARCH
                - IPC_LOCK
                - IPC_OWNER
                - LEASE
                - LINUX_IMMUTABLE
                - MAC_ADMIN
                - MAC_OVERRIDE
                - SYS_ADMIN
                - SYS_BOOT
                - SYS_MODULE
                - SYS_NICE
                - SYS_PACCT
                - SYS_PTRACE
                - SYS_RESOURCE
                - SYS_TIME
                - SYS_TTY_CONFIG
                - SYSLOG
                - WAKE_ALARM
          stdin: true
          tty: true
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 1

