# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.5.0-2-g5ecc8de
_src_path: gh:epics-containers/services-template-helm
athena_services: []
cluster_name: pollux
cluster_namespace: p47-beamline
description: p47 IOC Instances and Services
git_platform: github.com
ioc_group: p47
location: bl47p
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
