rabbitmq:
  auth:
    username: admin
    existingPasswordSecret: rabbitmq-secrets
    existingErlangSecret: rabbitmq-secrets
  extraPlugins: rabbitmq_jms_topic_exchange,rabbitmq_stomp
  persistence:
    enabled: false
  initScriptsCM: rabbitmq-init
  rbac:
    create: false
  serviceAccount:
    create: false
  networkPolicy:
    enabled: false
  extraContainerPorts:
    - name: stomp
      containerPort: 61613
  service:
    type: LoadBalancer
    loadBalancerIP: 172.23.168.213
    extraPorts:
      - name: stomp
        port: 61613
        targetPort: stomp
  resourcesPreset: medium
