# yaml-language-server: $schema=https://github.com/DiamondLightSource/FastCS/releases/download/2025.8.1-alpha.10/fastcs-service.schema.json
# for local testing of schema changes switch to:
### yaml-language-server: $schema=../../../fastcs/schemas/fastcs-service.schema.json

fastcs:
  image:
    repository: ghcr.io/srishtysajeev/fastcs-uarm
    tag: 2025.8.7
    pullPolicy: IfNotPresent

  iocConfig: /epics/ioc/config

  command:
    - fastcs-uArm 

  editable: false
  autostart: true
