kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.global.domain }}-opis-ingress"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ .Values.global.domain }}-opis.diamond.ac.uk"
  rules:
    - host: "{{ .Values.global.domain }}-opis.diamond.ac.uk"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: epics-opis
                port:
                  number: 80
